[package]
name = "crane"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.47", features = ["derive"] }
fuzzy-matcher = "0.3.7"
anyhow = "1.0.99"
toml = "0.9.6"
